/// see https://www.theiphonewiki.com/wiki/List_of_iPhones
/// see https://gist.github.com/adamawolf/3048717
const Map<String, String> iPhoneCodeMap = {
  'iPhone1,1': 'iPhone',
  'iPhone1,2': 'iPhone 3G',
  'iPhone2,1': 'iPhone 3GS',
  'iPhone3,1': 'iPhone 4',
  'iPhone3,2': 'iPhone 4',
  'iPhone3,3': 'iPhone 4',
  'iPhone4,1': 'iPhone 4S',
  'iPhone5,1': 'iPhone 5',
  'iPhone5,2': 'iPhone 5',
  'iPhone5,3': 'iPhone 5C',
  'iPhone5,4': 'iPhone 5C',
  'iPhone6,1': 'iPhone 5S',
  'iPhone6,2': 'iPhone 5S',
  'iPhone7,1': 'iPhone 6 Plus',
  'iPhone7,2': 'iPhone 6',
  'iPhone8,1': 'iPhone 6s',
  'iPhone8,2': 'iPhone 6s Plus',
  'iPhone8,3': 'iPhone SE',
  'iPhone8,4': 'iPhone SE',
  'iPhone9,1': 'iPhone 7',
  'iPhone9,2': 'iPhone 7 Plus',
  'iPhone9,3': 'iPhone 7',
  'iPhone9,4': 'iPhone 7 Plus',
  'iPhone10,1': 'iPhone 8',
  'iPhone10,2': 'iPhone 8 Plus',
  'iPhone10,3': 'iPhone X',
  'iPhone10,4': 'iPhone 8',
  'iPhone10,5': 'iPhone 8 Plus',
  'iPhone10,6': 'iPhone X',
  'iPhone11,2': 'iPhone XS',
  'iPhone11,4': 'iPhone XS Max',
  'iPhone11,6': 'iPhone XS Max',
  'iPhone11,8': 'iPhone XR',
  'iPhone12,1': 'iPhone 11',
  'iPhone12,3': 'iPhone 11 Pro',
  'iPhone12,5': 'iPhone 11 Pro Max',
  'iPad1,1': 'iPad',
  'iPad1,2': 'iPad',
  'iPad2,1': 'iPad 2',
  'iPad2,2': 'iPad 2',
  'iPad2,3': 'iPad 2',
  'iPad2,4': 'iPad 2',
  'iPad3,1': 'iPad 3',
  'iPad3,2': 'iPad 3',
  'iPad3,3': 'iPad 3',
  'iPad2,5': 'iPad mini',
  'iPad2,6': 'iPad mini',
  'iPad2,7': 'iPad mini',
  'iPad3,4': 'iPad 4',
  'iPad3,5': 'iPad 4',
  'iPad3,6': 'iPad 4',
  'iPad4,1': 'iPad Air',
  'iPad4,2': 'iPad Air',
  'iPad4,3': 'iPad Air',
  'iPad4,4': 'iPad mini Retina',
  'iPad4,5': 'iPad mini Retina',
  'iPad4,6': 'iPad mini Retina',
  'iPad4,7': 'iPad mini 3',
  'iPad4,8': 'iPad mini 3',
  'iPad4,9': 'iPad mini 3',
  'iPad5,1': 'iPad mini 4',
  'iPad5,2': 'iPad mini 4',
  'iPad5,3': 'iPad Air 2',
  'iPad5,4': 'iPad Air 2',
  'iPad6,3': 'iPad Pro',
  'iPad6,4': 'iPad Pro',
  'iPad6,7': 'iPad Pro',
  'iPad6,8': 'iPad Pro',
  'iPad6,11': 'iPad',
  'iPad6,12': 'iPad',
  'iPad7,1': 'iPad Pro 2',
  'iPad7,2': 'iPad Pro 2',
  'iPad7,3': 'iPad Pro',
  'iPad7,4': 'iPad Pro',
  'iPad7,5': 'iPad 6',
  'iPad7,6': 'iPad 6',
  'iPad7,11': 'iPad 7',
  'iPad7,12': 'iPad 7',
  'iPad8,1': 'iPad Pro 3',
  'iPad8,2': 'iPad Pro 3',
  'iPad8,3': 'iPad Pro 3',
  'iPad8,4': 'iPad Pro 3',
  'iPad8,5': 'iPad Pro 3',
  'iPad8,6': 'iPad Pro 3',
  'iPad8,7': 'iPad Pro 3',
  'iPad8,8': 'iPad Pro 3',
  'iPad11,1': 'iPad mini 5',
  'iPad11,2': 'iPad mini 5',
  'iPad11,3': 'iPad Air 3',
  'iPad11,4': 'iPad Air 3',
};

/// convert machine code to model
///
/// e.g. iPhone10,1 => iPhone 8
String iPhoneModel(String machine) =>
    iPhoneCodeMap[machine] ?? (machine.contains('iPad') ? 'iPad' : 'iPhone');
